version: "3.4"

services:
  postgres-db-dump:
    image: test:latest
    volumes:
      - /data/work/temp/temp:/var/lib/postgresql/dumps
    environment:
      PGDUMP_USER: postgres
      PGDUMP_PORT: 6301
      PGDUMP_HOST: '135.181.25.212'
      PGDUMP_DB: bike2work-reports
      PGPASSWORD_FILE: /var/lib/postgresql/dumps/bike2work-reports-pass.txt
      PGDUMP_MINUTE: 'true'